
token:
  secret: 'AYCde/9pYr4Xv33l71SsVUQUBIPyB0xcHvoYke6Pj3EIzTanVs6cifmXZBfXkpt9p9wDzTrI/qqIitbFpFL6JoHvVde+eEWfHMAbOnvMB0EqhM6R2LndYiU/kmkV0bZ4jWFNWBcmHJJnMGVJPPjFXodq//CeGfttnAgNLCePmIRY3OT6k/wN9VGbQL6Tu+qCVJriUtAStX0g1FXigSvirNscdYhJj43zdVJY3RoK2hFgu+yQZYGnPXVWNP8yv7xxYtEFU7U9s1wPmxLzxAQGc7DVHYHjhoJYqDW0lhiNryRfbst8CENlR7K2olDkfOV5CtWe2I9kR5MlgYSs+m+J6HfeD/6fiELLQXbgDZ1EOR6Wt6O88r+mrhMXIHdqEFuOnXgnqg29tBzneYHnm58LIwhh3kJrRnCj2eq2ORhd2veSRlX8iBKsr15Q+B+8fgjeHw3iW0630m89Lc0sKzh+5vqhg/tFz+LwqH/leUnywSDVb1jHJaaZejrjLWSJyLfRtlbzzPy7VYBYX3yhtaQ7m4zb9qThVrQkHwlMj7yjjQ2FFA=='
  expiration_time: 86400000
gateway:
  ip: 127.0.0.1



spring:
  datasource:
    url:  jdbc:h2:mem:testdb
    password: '{cipher}AYBlqEr5/CTlEQXKLE+We90hsQ+Cw+ePC64fmaha4aJb1MQ83olc42yFaHfoeenaNcPbxs9GNEV6FNvhFFjY09B2psPEJTl6OmbYYrgqIIS7CTTWXKSaUV8XQxkfOOWT6XizRNFztz05x+PeIOHbydoIH5r5+iSH7wrlWPgodIfeE8EXNY0gL4DX68OShgLijskRg2bsi1JNWEmJi3HyMwByEQqvDN8EGMyBj3mmlnKUcrS69iAz/qF5uRCcYf89F5XvSdvBqzfVAGEEU/MeXm0tCjqe9M1yqp3rB2jVxJDKMZd9UP7BiOAzm/7bDqNf3caII9PbvzgSrEO8VkyrzoZ2LcZQTkJlNjlKSRf+JZZ/j89Jw3XfU7Qj6OODgDA2aWkVE3hrf+vsnM4J3X2r78jp2w2TQ5Own5aG/f4a5ttaDiFqb8msM8r1j56HjnYa5bDXdh6LkLWRK7WC7axsf+DsPyDbSagxXFjp0Zxi1ZKCr+lf4OCkXDEVCboMUnCxH0A15pMECNUZy4JKBFliYZpn39Pu+B2dFY5W1pMp4lipv4raPGVhKLKdooacToaRADU='
    username: sa
    driver-class-name: org.h2.Driver

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
